name: Python Package

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #start_index: [ 0,100,200,300,400,500,600,700,800,900 ]
        start_index: [ 0 ]
        steps: [ 100 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: clone code
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/parserpp/data.git
          cp data/appList.csv  pkg.csv
          echo "clone success. cat info"
          ls

      - name: prepare install  requirements
        shell: bash
        continue-on-error: true
        run: |
          pip install -r requirements.txt

      - name: work
        shell: bash
        continue-on-error: true
        run: |
          python update_pkg_list_wandoujia.py  ${{ secrets.GTOKEN }} ${{ matrix.start_index }} ${{ matrix.steps }}

      - name: cat dir
        shell: bash
        continue-on-error: true
        run: |
          ls
          cat pkg_result.csv

      - name: cat chromedriver
        shell: bash
        continue-on-error: true
        run: |
          type chromedriver
          chromedriver --help

#      - name: test baseRequest
#        shell: bash
#        continue-on-error: true
#        run: |
#          python baseRequest.py

#      - name: Send mail
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.163.com
#          server_port: 465
#          #          server_address: smtp.gmail.com
#          #          server_port: 465
#          username: ${{ secrets.MAILUSERNAME }}
#          password: ${{ secrets.MAILPASSWORD }}
#          subject: "包名验证成果"
#          to: ${{ secrets.MAIL_LIST }}
#          from: GithubActions
#          secure: true
#          #  body:  |
#          #    Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully!
#          #    Commit msg: ${{ github.event.head_commit.message }}
#          #html_body: file://result.html
#          ignore_cert: true
#          priority: low
#          attachments: ./pkg_result.csv
