name: Python Package

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: clone code
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/parserpp/data.git
          cp data/appList.csv  pkg.csv
          echo "clone success. cat info"
          ls

      - name: prepare python env
        shell: bash
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          echo "===========env success=============="
          python pkg_list/update_pkg_list.py ${{ secrets.GTOKEN }}

      - name: ls cat info when success
        shell: bash
        continue-on-error: true
        run: ls

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          #          server_address: smtp.gmail.com
          #          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: "包名验证成果"
          to: ${{ secrets.MAIL_LIST }}
          from: GithubActions
          secure: true
          #  body:  |
          #    Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully!
          #    Commit msg: ${{ github.event.head_commit.message }}
          #html_body: file://result.html
          ignore_cert: true
          priority: low
          attachments: ./pkg_result.csv


#     - name: Install dependencies
#       run: |
#         conda env update --file environment.yml --name base
#     - name: Lint with flake8
#       run: |
#         conda install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         conda install pytest
#         pytest
